// HEADER ANIMATIONS
export const OVERLAY_TEXT_DURATION = 0.5;
export const OVERLAY_BACKGROUND_DURATION = 1;
export const TOTAL_OVERLAY_DURATION = 1.5;
export const HEADER_TEXT_DURATION = 0.7;

// PORTFOLIO ANIMATIONS
